title: Agentic Coding Handbook
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
permalink: pretty

# Color scheme and appearance
color_scheme: dark
search_enabled: true
heading_anchors: true

# Navigation
nav_sort: case_insensitive
# Enable pagination/navigation - ADD THIS
back_to_top: true
back_to_top_text: "Back to top"

# Footer
footer_content: 'Copyright &copy; 2025 Agentic Coding Handbook. Distributed by an <a href="https://github.com/tweag/agentic-coding-handbook/tree/main/LICENSE">MIT license.</a>'

# Search
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
