# Bandit configuration file
targets:
  - src/

# Skip these tests
skips:
  - B101 # assert used
  - B404 # subprocess without shell=True
  - B603 # subprocess with shell=True
  - B607 # start_process_with_partial_path

# Output format
output_format: screen
